name: Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit
    - name: Install OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
        unzip dependency-check-6.5.3-release.zip
        chmod +x dependency-check/bin/dependency-check.sh
    - name: Run security scan
      run: python amir.py .
    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: security-scan-results
        path: security-scan-results.txt
    - name: Comment PR
      uses: actions/github-script@v6
      if: always()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs')
          const scanResults = fs.readFileSync('security-scan-results.txt', 'utf8')
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## Security Scan Results\n\n```\n' + scanResults + '\n```'
          })