version: '3.8'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - api.env
    networks:
      - iceberg_env

networks:
  iceberg_env:
    external: true